### ISSUE TITLE
(Enhancement) Use jpdb.io API for realtime updated predictions

### ISSUE THREAD

**Issue by sujalwastaken** [getmane/jp-comprehension-predict#1]
You can use the [jpdb.io API](https://jpdb.stoplight.io/docs/jpdb/mgsimhgxpjpqe-jpdb-io-public-api) for achieving this. I can make an extension like this but I don't really need it that bad, so I thought I would just put it here in case someone else care.

**Comment by getmane** [comment]
hey, thanks for sharing (I didn't even see the API lol), I don't think there is any way to fetch user-reviewed vocab though, only vocab that is present in the user deck(s)

**Comment by sujalwastaken** [comment]
Yeah, even I did not know about it; had to literally dig through their discord server because [jpd-breader](https://github.com/max-kamps/jpd-breader.git) was using some sort of API to achieve this. I actually wanted to get this feature in jpd-breader what you extension is doing.

Well, there is a way to know what vocab is new, not-in-deck, due etc... with help of the API. For that you just have to [parse text](https://jpdb.stoplight.io/docs/jpdb/609bb98ccd378-parse-text) from the whole page and then check how much of the vocabulary is known. I think you can use the card_state value to get the current state of the card.

**Comment by getmane** [comment]
Ah, you are right there is a state for each card...
I was not familiar with jpd-breader, just thought to make something like that for myself. Anyways, thanks for the info, will dabble with the API 👍
